---
title: "Developing Data Products Week 2 Project: 11/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r,include=FALSE}
#Load libraries
library(readr)
library(dplyr)
library(leaflet)

```

```{r, include=FALSE}
#Read CSV of Top 10 BBQ places in Kansas City (data from Yelp)
urlfile <- ("https://raw.githubusercontent.com/fwchu07/DevelopingDataProducts_Wk2/gh-pages/bbqlist.csv")
bbqlist<-read_csv(url(urlfile))
bbqdf <-data.frame(bbqlist)

```


```{r,include=FALSE}
#Create categories for percentage of 5 star ratings
mycol = c("darkorange","purple","darkgreen","red","blue")
bbq <- bbqdf %>%
  mutate(perc = FiveStarRatings/TotalRatings) %>%
  mutate(color=cut(perc, breaks=c(-Inf, 0.55,0.6,0.65,0.7, Inf),labels=mycol))

```

The map below contains the Top 10 BBQ restaurants in the Kansas City area (identified by Yelp), categorized by percentage of 5-Star Reviews.
```{r,echo=FALSE,message=FALSE}
#Generate Map
bbq%>% 
  leaflet() %>%
  addTiles() %>%
  addCircleMarkers(color=bbq$color,popup=bbq$Name) %>%
  addLegend(title="Percentage of 5-Star Reviews",labels = c("50-55%","55-60%","60-65%","65-70%","70-75%"),colors=mycol)

```
